// Changing station IDs or qualifying airport aliases requires a new version.
// Display-name-only corrections may be made without changing the version.
module.exports = {
  version: '2026.1',
  stations: [
    { id: 'astoria', name: 'CGAS Astoria', airportCodes: ['KAST', 'AST'] },
    { id: 'atlantic-city', name: 'CGAS Atlantic City', airportCodes: ['KACY', 'ACY'] },
    { id: 'barbers-point', name: 'CGAS Barbers Point', airportCodes: ['PHJR', 'JRF'] },
    { id: 'borinquen', name: 'CGAS Borinquen', airportCodes: ['TJBQ', 'BQN'] },
    { id: 'cape-cod', name: 'CGAS Cape Cod', airportCodes: ['KFMH', 'FMH'] },
    { id: 'clearwater', name: 'CGAS Clearwater', airportCodes: ['KPIE', 'PIE'] },
    { id: 'corpus-christi', name: 'CGAS Corpus Christi', airportCodes: ['KCRP', 'CRP'] },
    { id: 'detroit', name: 'CGAS Detroit', airportCodes: ['KMTC', 'MTC'] },
    { id: 'elizabeth-city', name: 'CGAS Elizabeth City', airportCodes: ['KECG', 'ECG'] },
    { id: 'houston', name: 'CGAS Houston', airportCodes: ['KEFD', 'EFD'] },
    { id: 'humboldt-bay', name: 'CGAS Humboldt Bay', airportCodes: ['KACV', 'ACV'] },
    { id: 'kodiak', name: 'CGAS Kodiak', airportCodes: ['PADQ', 'ADQ'] },
    { id: 'miami', name: 'CGAS Miami', airportCodes: ['KOPF', 'OPF'] },
    { id: 'new-orleans', name: 'CGAS New Orleans', airportCodes: ['KNBG', 'NBG'] },
    { id: 'north-bend', name: 'CGAS North Bend', airportCodes: ['KOTH', 'OTH'] },
    { id: 'port-angeles', name: 'CGAS Port Angeles', airportCodes: ['KNOW', 'NOW'] },
    { id: 'sacramento', name: 'CGAS Sacramento', airportCodes: ['KMCC', 'MCC'] },
    { id: 'san-diego', name: 'CGAS San Diego', airportCodes: ['KLDR', 'LDR'] },
    { id: 'san-francisco', name: 'CGAS San Francisco', airportCodes: ['KSFO', 'SFO'] },
    { id: 'savannah', name: 'CGAS Savannah', airportCodes: ['KSVN', 'SVN'] },
    { id: 'sitka', name: 'CGAS Sitka', airportCodes: ['PASI', 'SIT'] },
    { id: 'traverse-city', name: 'CGAS Traverse City', airportCodes: ['KTVC', 'TVC'] },
    { id: 'ventura', name: 'CGAS Ventura', airportCodes: ['KNTD', 'NTD'] },
    { id: 'washington', name: 'CGAS Washington', airportCodes: ['KDCA', 'DCA'] },
    { id: 'hitron-jacksonville', name: 'HITRON Jacksonville', airportCodes: ['KVQQ', 'VQQ'] },
    { id: 'atc-mobile', name: 'ATC Mobile', airportCodes: ['KMOB', 'MOB'] },
  ],
};
